# Generated by Django 3.2.16 on 2023-03-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('allergy_name', models.CharField(blank=True, db_column='allergy_ name', max_length=20, null=True)),
            ],
            options={
                'db_table': 'allergy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MenuAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'menu_allergy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MenuImage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, max_length=20, null=True)),
                ('filepath', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'menu_image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MenuRecommendLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'menu_recommend_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NutritionInformation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ingredients', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('carbohydrates', models.IntegerField(blank=True, null=True)),
                ('sugar', models.IntegerField(blank=True, null=True)),
                ('protein', models.IntegerField(blank=True, null=True)),
                ('fat', models.IntegerField(blank=True, null=True)),
                ('trans_fat', models.IntegerField(blank=True, null=True)),
                ('saturation_fat', models.IntegerField(blank=True, null=True)),
                ('cholesterol', models.IntegerField(blank=True, null=True)),
                ('sodium', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nutrition_information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreferredMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.IntegerField()),
            ],
            options={
                'db_table': 'preferred_menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=45)),
                ('business_hours', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('category_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'restaurant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, max_length=20, null=True)),
                ('filepath', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'restaurant_image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fllename', models.CharField(blank=True, max_length=20, null=True)),
                ('filepath', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'review_image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'user_allergy',
                'managed': False,
            },
        ),
    ]
