# Generated by Django 3.2.16 on 2023-03-25 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jmc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergy',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='menuallergy',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='menurecommendlog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='nutritioninformation',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='preferredmenu',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userallergy',
            options={'managed': True},
        ),
    ]
