# Generated by Django 3.2.16 on 2023-03-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jmc', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
